[tool.poetry]
name = "ssmim"
version = "0.0.0"
description = "SSM for image density estimation"
authors = ["Justin Chiu <chiu.justin.t@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.*"
pandas = "*"
numpy = "*"
pyparsing = "*"
tqdm = "*"
tiktoken = "*"
openai = "*"
tenacity = "*"
scipy = "*"
pytest = "*"

torch = "*"
transformers = "*"
tokenizers = ">=0.13.3"
datasets = "*"
causal-conv1d = "*"
mamba-ssm = "*"

colorful = "*"
tyro = "*"
einops = "*"

wandb = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
